Metrics/LineLength: { Max: 112 }
Metrics/ClassLength: { Max: 240 }
Metrics/ModuleLength: { Max: 240 }
Metrics/CyclomaticComplexity: { Max: 8 }
Metrics/PerceivedComplexity: { Max: 8 }
Metrics/ParameterLists: { Max: 8 }
Metrics/MethodLength: { Max: 12 }
Metrics/MethodLength: { Max: 24 }
Metrics/BlockNesting: { Max: 4 }
Metrics/AbcSize: { Max: 20 }

Style/IndentHash: { EnforcedStyle: consistent }
Style/SignalException: { EnforcedStyle: only_raise }
Style/Semicolon: { AllowAsExpressionSeparator: true }
Style/StringLiteralsInInterpolation: { EnforcedStyle: double_quotes }
Style/RegexpLiteral: { EnforcedStyle: slashes, AllowInnerSlashes: true }
Style/MultilineMethodCallIndentation: { EnforcedStyle: indented }
Style/MultilineOperationIndentation: { EnforcedStyle: indented }
Style/FirstParameterIndentation: { EnforcedStyle: consistent }
Style/FrozenStringLiteralComment: { EnforceStyle: always }
Style/StringLiterals: { EnforcedStyle: double_quotes }
Style/IndentArray: { EnforcedStyle: consistent }
Style/ExtraSpacing: { AllowForAlignment: true }

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%q': '{}'
    '%Q': '{}'
    '%r': '!!'
    '%s': '()'
    '%w': '()'
    '%W': '()'
    '%x': '()'

Style/HashSyntax:                     { Enabled: false }
Style/AlignArray:                     { Enabled: false }
Style/StringLiterals:                 { Enabled: false }
Style/Documentation:                  { Enabled: false }
Style/DoubleNegation:                 { Enabled: false }
Style/UnneededCapitalW:               { Enabled: false }
Style/SpaceAroundOperators:           { Enabled: false }
Style/MultilineTernaryOperator:       { Enabled: false }
Style/EmptyLinesAroundModuleBody:     { Enabled: false }
Style/FrozenStringLiteralComment:     { Enabled:  true }
Style/EmptyLinesAroundAccessModifier: { Enabled: false }
Style/BracesAroundHashParameters:     { Enabled: false }
Lint/UselessAccessModifier:           { Enabled: false }
Style/SpaceInsideBrackets:            { Enabled: false }
Style/IfUnlessModifier:               { Enabled: false }
Style/AlignParameters:                { Enabled: false }
Style/ModuleFunction:                 { Enabled: false }
Style/RescueModifier:                 { Enabled: false }
Style/GuardClause:                    { Enabled: false }
Style/FileName:                       { Enabled: false }
Style/RedundantReturn:                { Enabled: false }
Lint/UnusedMethodArgument:            { Enabled: false }

AllCops:
  TargetRubyVersion: 2.0
  Include:
    - lib/**/*.rb

  Exclude:
    - .rubocop.yml
    - .codeclimate.yml
    - .travis.yml
    - .gitignore
    - .rspec

    - Gemfile.lock
    - CHANGELOG.md
    - readme.md
    - README.md
    - Readme.md
    - ReadMe.md
    - COPYING
    - LICENSE
    - NEWS

    - test/**/*
    - vendor/**/*
    - features/**/*
    - script/**/*
    - spec/**/*
